#!/usr/bin/env python3
"""Sync environment variables from the master secrets file to app .env.local files.

Master source: voice/v3-dual/.env
Targets:
  - apps/mobile/.env.local
  - apps/landing/.env.local

Run from the repo root:
    python scripts/sync-env-local.py

Use --dry-run to preview which keys would be written without touching files.
"""
import argparse
import re
import sys
from datetime import datetime
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
MASTER_ENV = REPO_ROOT / "voice" / "v3-dual" / ".env"

TARGETS = {
    "mobile": {
        "path": REPO_ROOT / "apps" / "mobile" / ".env.local",
        "keys": [
            "VITE_VOICE_SERVER_URL",
            "VITE_VOICE_SERVER_API_KEY",
            "VITE_SENTRY_DSN",
            "VITE_APP_VERSION",
            "VITE_VERCEL_ENV",
            "VITE_USER_NAME",
            "VITE_ENABLED_CHARACTERS",
            "VITE_FEATURED_CHARACTER",
        ],
        "defaults": {
            "VITE_VOICE_SERVER_URL": "wss://casa-voice-agent.fly.dev/ws/voice",
        },
    },
    "landing": {
        "path": REPO_ROOT / "apps" / "landing" / ".env.local",
        "keys": [
            "SUPABASE_URL",
            "SUPABASE_ANON_KEY",
            "SUPABASE_SERVICE_ROLE_KEY",
            "OPENAI_API_KEY",
            "OPENAI_REALTIME_MODEL",
            "NEXT_PUBLIC_SITE_URL",
            "NEXT_PUBLIC_API_URL",
            "VITE_API_URL",
            "VITE_SUPABASE_URL",
            "VITE_SUPABASE_ANON_KEY",
            "VITE_SUPABASE_SECRET_KEY",
            "NEXT_TELEMETRY_DISABLED",
            "NODE_ENV",
            # Legacy Cloudflare keys — add to master only if you still use Cloudflare STT/LLM
            # "CLOUDFLARE_API_TOKEN",
            # "CLOUDFLARE_ACCOUNT_ID",
        ],
        "defaults": {
            "NEXT_PUBLIC_SITE_URL": "https://casa-landing.vercel.app",
            "OPENAI_REALTIME_MODEL": "gpt-realtime-2",
            "NODE_ENV": "production",
        },
    },
}


def parse_env(path: Path) -> dict[str, str]:
    """Parse key=value pairs from an .env file. Keeps the last value for duplicates."""
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        match = re.match(r"^([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$", stripped)
        if match:
            key, val = match.groups()
            values[key] = val
    return values


def build_env_local(app_name: str, master: dict[str, str], dry_run: bool) -> None:
    target = TARGETS[app_name]
    target_path: Path = target["path"]
    defaults = target.get("defaults", {})

    existing = parse_env(target_path) if target_path.exists() else {}

    written: list[str] = []
    missing: list[str] = []
    defaulted: list[str] = []

    out_lines = [
        f"# Auto-generated by scripts/sync-env-local.py on {datetime.now().isoformat()}",
        f"# Source: {MASTER_ENV.relative_to(REPO_ROOT)}",
        "# Do NOT commit this file.",
        "",
    ]

    for key in target["keys"]:
        if key in master and master[key].strip():
            value = master[key]
            written.append(key)
        elif key in existing and existing[key].strip():
            # Keep existing value if master doesn't have it.
            value = existing[key]
            written.append(key)
        elif key in defaults:
            value = defaults[key]
            defaulted.append(key)
        else:
            missing.append(key)
            continue

        out_lines.append(f"{key}={value}")

    if dry_run:
        print(f"\n[{app_name}] would write to {target_path.relative_to(REPO_ROOT)}")
        print(f"  written ({len(written)}): {', '.join(written) or 'none'}")
        print(f"  defaulted ({len(defaulted)}): {', '.join(defaulted) or 'none'}")
        print(f"  missing ({len(missing)}): {', '.join(missing) or 'none'}")
        return

    target_path.parent.mkdir(parents=True, exist_ok=True)
    target_path.write_text("\n".join(out_lines) + "\n", encoding="utf-8")

    print(f"\n[{app_name}] wrote {target_path.relative_to(REPO_ROOT)}")
    print(f"  written ({len(written)}): {', '.join(written) or 'none'}")
    if defaulted:
        print(f"  defaulted ({len(defaulted)}): {', '.join(defaulted)}")
    if missing:
        print(f"  missing ({len(missing)}): {', '.join(missing)}")


def main() -> int:
    parser = argparse.ArgumentParser(description="Sync secrets from master .env to app .env.local files.")
    parser.add_argument("--dry-run", action="store_true", help="Preview changes without writing files.")
    args = parser.parse_args()

    if not MASTER_ENV.exists():
        print(f"Master env not found: {MASTER_ENV}", file=sys.stderr)
        return 1

    master = parse_env(MASTER_ENV)

    if args.dry_run:
        print("DRY RUN — no files will be modified")

    for app_name in TARGETS:
        build_env_local(app_name, master, args.dry_run)

    return 0


if __name__ == "__main__":
    sys.exit(main())
