import type { Character } from '@/types';

export const characters: Character[] = [
  {
    slug: 'corvo',
    name: 'Corvo',
    description: 'Corvo — Corvo means Crow in Italian',
    subtitle: 'Introduction',
    italianMeaning: 'Corvo means Crow in Italian',
    accentColor: '#6b7fd7',
    accentHue: 230,
    category: 'animal',
    traits: ['Friendly', 'Curious', 'Supportive', 'Playful'],
    portrait: '/characters/corvo.png',
    showcase: '/characters/corvo.png',
    voiceIntro: '/audio/corvo-intro.mp3',
    videoSrc: '/videos/corvo_idle.mp4',
    modes: {
      play: ['Story Time', 'Music & Rhythm', 'Geography', 'STEM Sparks'],
      learn: ['All Languages', 'Homework Helper', 'Coding'],
      support: ['Calm & Breathe', 'Milestones', 'Teaching Mode'],
    },
  },
  {
    slug: 'gufo',
    name: 'Gufo',
    description: 'Gufo — Gufo means Owl in Italian',
    subtitle: 'Introduction',
    italianMeaning: 'Gufo means Owl in Italian',
    accentColor: '#c49a6c',
    accentHue: 30,
    category: 'animal',
    traits: ['Friendly', 'Curious', 'Supportive', 'Playful'],
    portrait: '/characters/gufo.png',
    showcase: '/characters/gufo.png',
    voiceIntro: '/audio/gufo-intro.mp3',
    videoSrc: '/videos/gufo_idle.mp4',
    modes: {
      play: ['Story Time', 'Music & Rhythm', 'Geography', 'STEM Sparks'],
      learn: ['All Languages', 'Homework Helper', 'Coding'],
      support: ['Calm & Breathe', 'Milestones', 'Teaching Mode'],
    },
  },
  {
    slug: 'orsetto',
    name: 'Orsetto',
    description: 'Orsetto — Orsetto means Little Bear in Italian',
    subtitle: 'Introduction',
    italianMeaning: 'Orsetto means Little Bear in Italian',
    accentColor: '#d4a843',
    accentHue: 42,
    category: 'animal',
    traits: ['Friendly', 'Curious', 'Supportive', 'Playful'],
    portrait: '/characters/orsetto.png',
    showcase: '/characters/orsetto.png',
    voiceIntro: '/audio/orsetto-intro.mp3',
    videoSrc: '/videos/orsetto_idle.mp4',
    modes: {
      play: ['Story Time', 'Music & Rhythm', 'Geography', 'STEM Sparks'],
      learn: ['All Languages', 'Homework Helper', 'Coding'],
      support: ['Calm & Breathe', 'Milestones', 'Teaching Mode'],
    },
  },
  {
    slug: 'coniglio',
    name: 'Coniglio',
    description: 'Coniglio — Coniglio means Bunny in Italian',
    subtitle: 'Introduction',
    italianMeaning: 'Coniglio means Bunny in Italian',
    accentColor: '#f5a0b5',
    accentHue: 345,
    category: 'animal',
    traits: ['Friendly', 'Curious', 'Supportive', 'Playful'],
    portrait: '/characters/coniglio.png',
    showcase: '/characters/coniglio.png',
    voiceIntro: '/audio/coniglio-intro.mp3',
    videoSrc: '/videos/coniglio_idle.mp4',
    modes: {
      play: ['Story Time', 'Music & Rhythm', 'Geography', 'STEM Sparks'],
      learn: ['All Languages', 'Homework Helper', 'Coding'],
      support: ['Calm & Breathe', 'Milestones', 'Teaching Mode'],
    },
  },
  {
    slug: 'tartaruga',
    name: 'Tartaruga',
    description: 'Tartaruga — Tartaruga means Sea Turtle in Italian',
    subtitle: 'Introduction',
    italianMeaning: 'Tartaruga means Sea Turtle in Italian',
    accentColor: '#5cb88a',
    accentHue: 155,
    category: 'animal',
    traits: ['Friendly', 'Curious', 'Supportive', 'Playful'],
    portrait: '/characters/tartaruga.webp',
    showcase: '/characters/tartaruga-showcase.png',
    voiceIntro: '/audio/tartaruga-intro.mp3',
    videoSrc: '/videos/tartaruga_idle.mp4',
    modes: {
      play: ['Story Time', 'Music & Rhythm', 'Geography', 'STEM Sparks'],
      learn: ['All Languages', 'Homework Helper', 'Coding'],
      support: ['Calm & Breathe', 'Milestones', 'Teaching Mode'],
    },
  },
  {
    slug: 'elefante',
    name: 'Elefante',
    description: 'Elefante — Elefante means Elephant in Italian',
    subtitle: 'Introduction',
    italianMeaning: 'Elefante means Elephant in Italian',
    accentColor: '#8a9bb5',
    accentHue: 215,
    category: 'animal',
    traits: ['Friendly', 'Curious', 'Supportive', 'Playful'],
    portrait: '/characters/elefante.png',
    showcase: '/characters/elefante.png',
    voiceIntro: '/audio/elefante-intro.mp3',
    videoSrc: '/videos/elefante_idle.mp4',
    modes: {
      play: ['Story Time', 'Music & Rhythm', 'Geography', 'STEM Sparks'],
      learn: ['All Languages', 'Homework Helper', 'Coding'],
      support: ['Calm & Breathe', 'Milestones', 'Teaching Mode'],
    },
  },
  {
    slug: 'leone',
    name: 'Leone',
    description: 'Leone — Leone means Lion in Italian',
    subtitle: 'Introduction',
    italianMeaning: 'Leone means Lion in Italian',
    accentColor: '#e8913a',
    accentHue: 28,
    category: 'animal',
    traits: ['Friendly', 'Curious', 'Supportive', 'Playful'],
    portrait: '/characters/leone.png',
    showcase: '/characters/leone.png',
    voiceIntro: '/audio/leone-intro.mp3',
    videoSrc: '/videos/leone_idle.mp4',
    modes: {
      play: ['Story Time', 'Music & Rhythm', 'Geography', 'STEM Sparks'],
      learn: ['All Languages', 'Homework Helper', 'Coding'],
      support: ['Calm & Breathe', 'Milestones', 'Teaching Mode'],
    },
  },
  {
    slug: 'delfino',
    name: 'Delfino',
    description: 'Delfino — Delfino means Dolphin in Italian',
    subtitle: 'Introduction',
    italianMeaning: 'Delfino means Dolphin in Italian',
    accentColor: '#7ab8d4',
    accentHue: 197,
    category: 'animal',
    traits: ['Friendly', 'Curious', 'Supportive', 'Playful'],
    portrait: '/characters/delfino.png',
    showcase: '/characters/delfino.png',
    voiceIntro: '/audio/delfino-intro.mp3',
    videoSrc: '/videos/delfino_idle.mp4',
    modes: {
      play: ['Story Time', 'Music & Rhythm', 'Geography', 'STEM Sparks'],
      learn: ['All Languages', 'Homework Helper', 'Coding'],
      support: ['Calm & Breathe', 'Milestones', 'Teaching Mode'],
    },
  },
  {
    slug: 'volpe',
    name: 'Volpe',
    description: 'Volpe — Volpe means Fox in Italian',
    subtitle: 'Introduction',
    italianMeaning: 'Volpe means Fox in Italian',
    accentColor: '#e07a3e',
    accentHue: 20,
    category: 'animal',
    traits: ['Friendly', 'Curious', 'Supportive', 'Playful'],
    portrait: '/characters/volpe.png',
    showcase: '/characters/volpe.png',
    voiceIntro: '/audio/volpe-intro.mp3',
    videoSrc: '/videos/volpe_idle.mp4',
    modes: {
      play: ['Story Time', 'Music & Rhythm', 'Geography', 'STEM Sparks'],
      learn: ['All Languages', 'Homework Helper', 'Coding'],
      support: ['Calm & Breathe', 'Milestones', 'Teaching Mode'],
    },
  },
  {
    slug: 'drago',
    name: 'Drago',
    description: 'Drago — Drago means Dragon in Italian',
    subtitle: 'Introduction',
    italianMeaning: 'Drago means Dragon in Italian',
    accentColor: '#5cdb7c',
    accentHue: 135,
    category: 'animal',
    traits: ['Friendly', 'Curious', 'Supportive', 'Playful'],
    portrait: '/characters/drago.png',
    showcase: '/characters/drago.png',
    voiceIntro: '/audio/drago-intro.mp3',
    videoSrc: '/videos/drago_idle.mp4',
    modes: {
      play: ['Story Time', 'Music & Rhythm', 'Geography', 'STEM Sparks'],
      learn: ['All Languages', 'Homework Helper', 'Coding'],
      support: ['Calm & Breathe', 'Milestones', 'Teaching Mode'],
    },
  },
  {
    slug: 'xolo',
    name: 'Xolo',
    description: 'Xolo — Xolo is a Xoloitzcuintli, the ancient Aztec dog',
    subtitle: 'Introduction',
    italianMeaning: 'Xolo is a Xoloitzcuintli, the ancient Aztec dog',
    accentColor: '#b8926a',
    accentHue: 32,
    category: 'animal',
    traits: ['Friendly', 'Curious', 'Supportive', 'Playful'],
    portrait: '/characters/xolo.png',
    showcase: '/characters/xolo.png',
    voiceIntro: '/audio/xolo-intro.mp3',
    videoSrc: '/videos/ambient-bokeh.mp4',
    modes: {
      play: ['Story Time', 'Music & Rhythm', 'Geography', 'STEM Sparks'],
      learn: ['All Languages', 'Homework Helper', 'Coding'],
      support: ['Calm & Breathe', 'Milestones', 'Teaching Mode'],
    },
  },
  {
    slug: 'scheletro',
    name: 'Scheletro',
    description: 'Scheletro — Scheletro means Skeleton in Italian — The Funny Bones',
    subtitle: 'Introduction',
    italianMeaning: 'Scheletro means Skeleton in Italian — The Funny Bones',
    accentColor: '#d7d7d7',
    accentHue: 0,
    category: 'animal',
    traits: ['Friendly', 'Curious', 'Supportive', 'Playful'],
    portrait: '/characters/scheletro.png',
    showcase: '/characters/scheletro.png',
    voiceIntro: '/audio/scheletro-intro.mp3',
    videoSrc: '/videos/scheletro_idle.mp4',
    modes: {
      play: ['Story Time', 'Music & Rhythm', 'Geography', 'STEM Sparks'],
      learn: ['All Languages', 'Homework Helper', 'Coding'],
      support: ['Calm & Breathe', 'Milestones', 'Teaching Mode'],
    },
  },
  {
    slug: 'ragno',
    name: 'Ragno',
    description: 'Ragno — Ragno means Spider in Italian — The Web Artist',
    subtitle: 'Introduction',
    italianMeaning: 'Ragno means Spider in Italian — The Web Artist',
    accentColor: '#8a6fd7',
    accentHue: 260,
    category: 'animal',
    traits: ['Friendly', 'Curious', 'Supportive', 'Playful'],
    portrait: '/characters/ragno.png',
    showcase: '/characters/ragno.png',
    voiceIntro: '/audio/ragno-intro.mp3',
    videoSrc: '/videos/ragno_idle.mp4',
    modes: {
      play: ['Story Time', 'Music & Rhythm', 'Geography', 'STEM Sparks'],
      learn: ['All Languages', 'Homework Helper', 'Coding'],
      support: ['Calm & Breathe', 'Milestones', 'Teaching Mode'],
    },
  },
  {
    slug: 'veloce',
    name: 'Veloce',
    description: 'Veloce — Veloce means Fast in Italian — The Speedy Rabbit',
    subtitle: 'Introduction',
    italianMeaning: 'Veloce means Fast in Italian — The Speedy Rabbit',
    accentColor: '#d7933e',
    accentHue: 35,
    category: 'animal',
    traits: ['Friendly', 'Curious', 'Supportive', 'Playful'],
    portrait: '/characters/veloce.png',
    showcase: '/characters/veloce.png',
    voiceIntro: '/audio/veloce-intro.mp3',
    videoSrc: '/videos/veloce_idle.mp4',
    modes: {
      play: ['Story Time', 'Music & Rhythm', 'Geography', 'STEM Sparks'],
      learn: ['All Languages', 'Homework Helper', 'Coding'],
      support: ['Calm & Breathe', 'Milestones', 'Teaching Mode'],
    },
  },
  {
    slug: 'stellino',
    name: 'Stellino',
    description: 'Stellino — Stellino means Little Star in Italian — The Dreamer',
    subtitle: 'Introduction',
    italianMeaning: 'Stellino means Little Star in Italian — The Dreamer',
    accentColor: '#d7a3d7',
    accentHue: 290,
    category: 'object',
    traits: ['Friendly', 'Curious', 'Supportive', 'Playful'],
    portrait: '/characters/stellino.png',
    showcase: '/characters/stellino.png',
    voiceIntro: '/audio/stellino-intro.mp3',
    videoSrc: '/videos/ambient-bokeh.mp4',
    modes: {
      play: ['Story Time', 'Music & Rhythm', 'Geography', 'STEM Sparks'],
      learn: ['All Languages', 'Homework Helper', 'Coding'],
      support: ['Calm & Breathe', 'Milestones', 'Teaching Mode'],
    },
  },
  {
    slug: 'sacco',
    name: 'Sacco',
    description: 'Sacco — Sacco means Sack in Italian — The DJ Sack',
    subtitle: 'Introduction',
    italianMeaning: 'Sacco means Sack in Italian — The DJ Sack',
    accentColor: '#d7c36f',
    accentHue: 45,
    category: 'object',
    traits: ['Friendly', 'Curious', 'Supportive', 'Playful'],
    portrait: '/characters/sacco.png',
    showcase: '/characters/sacco.png',
    voiceIntro: '/audio/sacco-intro.mp3',
    videoSrc: '/videos/sacco_idle.mp4',
    modes: {
      play: ['Story Time', 'Music & Rhythm', 'Geography', 'STEM Sparks'],
      learn: ['All Languages', 'Homework Helper', 'Coding'],
      support: ['Calm & Breathe', 'Milestones', 'Teaching Mode'],
    },
  },
  {
    slug: 'spugna',
    name: 'Spugna',
    description: 'Spugna — Spugna means Sponge in Italian',
    subtitle: 'Introduction',
    italianMeaning: 'Spugna means Sponge in Italian',
    accentColor: '#d7c36f',
    accentHue: 45,
    category: 'animal',
    traits: ['Friendly', 'Curious', 'Supportive', 'Playful'],
    portrait: '/characters/spugna.png',
    showcase: '/characters/spugna.png',
    voiceIntro: '/audio/spugna-intro.mp3',
    videoSrc: '/videos/spugna_idle.mp4',
    modes: {
      play: ['Story Time', 'Music & Rhythm', 'Geography', 'STEM Sparks'],
      learn: ['All Languages', 'Homework Helper', 'Coding'],
      support: ['Calm & Breathe', 'Milestones', 'Teaching Mode'],
    },
  },
  {
    slug: 'rocco',
    name: 'Rocco',
    description: 'Rocco — Rocco is a Cockroach — Rock Frontman',
    subtitle: 'Introduction',
    italianMeaning: 'Rocco is a Cockroach — Rock Frontman',
    accentColor: '#d74a3e',
    accentHue: 10,
    category: 'animal',
    traits: ['Friendly', 'Curious', 'Supportive', 'Playful'],
    portrait: '/characters/rocco.png',
    showcase: '/characters/rocco.png',
    voiceIntro: '/audio/rocco-intro.mp3',
    videoSrc: '/videos/rocco_idle.mp4',
    modes: {
      play: ['Story Time', 'Music & Rhythm', 'Geography', 'STEM Sparks'],
      learn: ['All Languages', 'Homework Helper', 'Coding'],
      support: ['Calm & Breathe', 'Milestones', 'Teaching Mode'],
    },
  },
  {
    slug: 'vinile',
    name: 'Vinile',
    description: 'Vinile — Vinile means Vinyl in Italian — The Record Collector',
    subtitle: 'Introduction',
    italianMeaning: 'Vinile means Vinyl in Italian — The Record Collector',
    accentColor: '#7a6fd7',
    accentHue: 250,
    category: 'animal',
    traits: ['Friendly', 'Curious', 'Supportive', 'Playful'],
    portrait: '/characters/vinile.png',
    showcase: '/characters/vinile.png',
    voiceIntro: '/audio/vinile-intro.mp3',
    videoSrc: '/videos/ambient-bokeh.mp4',
    modes: {
      play: ['Story Time', 'Music & Rhythm', 'Geography', 'STEM Sparks'],
      learn: ['All Languages', 'Homework Helper', 'Coding'],
      support: ['Calm & Breathe', 'Milestones', 'Teaching Mode'],
    },
  },
  {
    slug: 'battito',
    name: 'Battito',
    description: 'Battito — Battito means Heartbeat in Italian',
    subtitle: 'Introduction',
    italianMeaning: 'Battito means Heartbeat in Italian',
    accentColor: '#5c7ad7',
    accentHue: 220,
    category: 'animal',
    traits: ['Friendly', 'Curious', 'Supportive', 'Playful'],
    portrait: '/characters/battito.png',
    showcase: '/characters/battito.png',
    voiceIntro: '/audio/battito-intro.mp3',
    videoSrc: '/videos/battito_idle.mp4',
    modes: {
      play: ['Story Time', 'Music & Rhythm', 'Geography', 'STEM Sparks'],
      learn: ['All Languages', 'Homework Helper', 'Coding'],
      support: ['Calm & Breathe', 'Milestones', 'Teaching Mode'],
    },
  },
  {
    slug: 'onda',
    name: 'Onda',
    description: 'Onda — Onda means Wave in Italian — The Surf Punk',
    subtitle: 'Introduction',
    italianMeaning: 'Onda means Wave in Italian — The Surf Punk',
    accentColor: '#3ed7d7',
    accentHue: 180,
    category: 'animal',
    traits: ['Friendly', 'Curious', 'Supportive', 'Playful'],
    portrait: '/characters/onda.png',
    showcase: '/characters/onda.png',
    voiceIntro: '/audio/onda-intro.mp3',
    videoSrc: '/videos/onda_idle.mp4',
    modes: {
      play: ['Story Time', 'Music & Rhythm', 'Geography', 'STEM Sparks'],
      learn: ['All Languages', 'Homework Helper', 'Coding'],
      support: ['Calm & Breathe', 'Milestones', 'Teaching Mode'],
    },
  },
  {
    slug: 'maestra',
    name: 'Maestra',
    description: 'Maestra — Maestra means Teacher in Italian',
    subtitle: 'Introduction',
    italianMeaning: 'Maestra means Teacher in Italian',
    accentColor: '#d76f8a',
    accentHue: 340,
    category: 'person',
    traits: ['Friendly', 'Curious', 'Supportive', 'Playful'],
    portrait: '/characters/maestra.png',
    showcase: '/characters/maestra.png',
    voiceIntro: '/audio/maestra-intro.mp3',
    videoSrc: '/videos/maestra_idle.mp4',
    modes: {
      play: ['Story Time', 'Music & Rhythm', 'Geography', 'STEM Sparks'],
      learn: ['All Languages', 'Homework Helper', 'Coding'],
      support: ['Calm & Breathe', 'Milestones', 'Teaching Mode'],
    },
  },
  {
    slug: 'costruttore',
    name: 'Costruttore',
    description: 'Costruttore — Costruttore means Builder in Italian',
    subtitle: 'Introduction',
    italianMeaning: 'Costruttore means Builder in Italian',
    accentColor: '#d4a843',
    accentHue: 42,
    category: 'person',
    traits: ['Friendly', 'Curious', 'Supportive', 'Playful'],
    portrait: '/characters/costruttore.png',
    showcase: '/characters/costruttore.png',
    voiceIntro: '/audio/costruttore-intro.mp3',
    videoSrc: '/videos/costruttore_idle.mp4',
    modes: {
      play: ['Story Time', 'Music & Rhythm', 'Geography', 'STEM Sparks'],
      learn: ['All Languages', 'Homework Helper', 'Coding'],
      support: ['Calm & Breathe', 'Milestones', 'Teaching Mode'],
    },
  },
  {
    slug: 'dottore',
    name: 'Dottore',
    description: 'Dottore — Dottore means Doctor in Italian',
    subtitle: 'Introduction',
    italianMeaning: 'Dottore means Doctor in Italian',
    accentColor: '#7ad75c',
    accentHue: 100,
    category: 'person',
    traits: ['Friendly', 'Curious', 'Supportive', 'Playful'],
    portrait: '/characters/dottore.png',
    showcase: '/characters/dottore.png',
    voiceIntro: '/audio/dottore-intro.mp3',
    videoSrc: '/videos/dottore_idle.mp4',
    modes: {
      play: ['Story Time', 'Music & Rhythm', 'Geography', 'STEM Sparks'],
      learn: ['All Languages', 'Homework Helper', 'Coding'],
      support: ['Calm & Breathe', 'Milestones', 'Teaching Mode'],
    },
  },
  {
    slug: 'pietro',
    name: 'Pietro',
    description: 'Pietro — Pietro is the Founder of Casa Companion — The Leader',
    subtitle: 'Introduction',
    italianMeaning: 'Pietro is the Founder of Casa Companion — The Leader',
    accentColor: '#6f8ad7',
    accentHue: 220,
    category: 'person',
    traits: ['Friendly', 'Curious', 'Supportive', 'Playful'],
    portrait: '/characters/pietro.png',
    showcase: '/characters/pietro.png',
    voiceIntro: '/audio/pietro-intro.mp3',
    videoSrc: '/videos/pietro_idle.mp4',
    modes: {
      play: ['Story Time', 'Music & Rhythm', 'Geography', 'STEM Sparks'],
      learn: ['All Languages', 'Homework Helper', 'Coding'],
      support: ['Calm & Breathe', 'Milestones', 'Teaching Mode'],
    },
  },
  {
    slug: 'borsa',
    name: 'Borsa',
    description: 'Borsa — Borsa means Purse/Bag in Italian — The Fashionista',
    subtitle: 'Introduction',
    italianMeaning: 'Borsa means Purse/Bag in Italian — The Fashionista',
    accentColor: '#6fd7a3',
    accentHue: 150,
    category: 'animal',
    traits: ['Friendly', 'Curious', 'Supportive', 'Playful'],
    portrait: '/characters/borsa.png',
    showcase: '/characters/borsa.png',
    voiceIntro: '/audio/borsa-intro.mp3',
    videoSrc: '/videos/borsa_idle.mp4',
    modes: {
      play: ['Story Time', 'Music & Rhythm', 'Geography', 'STEM Sparks'],
      learn: ['All Languages', 'Homework Helper', 'Coding'],
      support: ['Calm & Breathe', 'Milestones', 'Teaching Mode'],
    },
  },
  {
    slug: 'mamma',
    name: 'Mamma',
    description: 'Mamma — Mamma means Mom in Italian — The Nurturer',
    subtitle: 'Introduction',
    italianMeaning: 'Mamma means Mom in Italian — The Nurturer',
    accentColor: '#d76fd7',
    accentHue: 300,
    category: 'animal',
    traits: ['Friendly', 'Curious', 'Supportive', 'Playful'],
    portrait: '/characters/mamma.png',
    showcase: '/characters/mamma.png',
    voiceIntro: '/audio/mamma-intro.mp3',
    videoSrc: '/videos/mamma_idle.mp4',
    modes: {
      play: ['Story Time', 'Music & Rhythm', 'Geography', 'STEM Sparks'],
      learn: ['All Languages', 'Homework Helper', 'Coding'],
      support: ['Calm & Breathe', 'Milestones', 'Teaching Mode'],
    },
  },
  {
    slug: 'verita',
    name: 'Verita',
    description: 'Verita — Verita is an Eagle — Truth Eagle',
    subtitle: 'Introduction',
    italianMeaning: 'Verita is an Eagle — Truth Eagle',
    accentColor: '#6f8ad7',
    accentHue: 220,
    category: 'animal',
    traits: ['Friendly', 'Curious', 'Supportive', 'Playful'],
    portrait: '/characters/verita.png',
    showcase: '/characters/verita.png',
    voiceIntro: '/audio/verita-intro.mp3',
    videoSrc: '/videos/verita_idle.mp4',
    modes: {
      play: ['Story Time', 'Music & Rhythm', 'Geography', 'STEM Sparks'],
      learn: ['All Languages', 'Homework Helper', 'Coding'],
      support: ['Calm & Breathe', 'Milestones', 'Teaching Mode'],
    },
  },
  {
    slug: 'forza',
    name: 'Forza',
    description: 'Forza — Forza means Strength in Italian',
    subtitle: 'Introduction',
    italianMeaning: 'Forza means Strength in Italian',
    accentColor: '#d7933e',
    accentHue: 30,
    category: 'animal',
    traits: ['Friendly', 'Curious', 'Supportive', 'Playful'],
    portrait: '/characters/forza.png',
    showcase: '/characters/forza.png',
    voiceIntro: '/audio/forza-intro.mp3',
    videoSrc: '/videos/forza_idle.mp4',
    modes: {
      play: ['Story Time', 'Music & Rhythm', 'Geography', 'STEM Sparks'],
      learn: ['All Languages', 'Homework Helper', 'Coding'],
      support: ['Calm & Breathe', 'Milestones', 'Teaching Mode'],
    },
  },
  {
    slug: 'bella',
    name: 'Bella',
    description: 'Bella — Bella means Beautiful in Italian',
    subtitle: 'Introduction',
    italianMeaning: 'Bella means Beautiful in Italian',
    accentColor: '#d66fd7',
    accentHue: 300,
    category: 'animal',
    traits: ['Friendly', 'Curious', 'Supportive', 'Playful'],
    portrait: '/characters/bella.png',
    showcase: '/characters/bella.png',
    voiceIntro: '/audio/bella-intro.mp3',
    videoSrc: '/videos/bella_idle.mp4',
    modes: {
      play: ['Story Time', 'Music & Rhythm', 'Geography', 'STEM Sparks'],
      learn: ['All Languages', 'Homework Helper', 'Coding'],
      support: ['Calm & Breathe', 'Milestones', 'Teaching Mode'],
    },
  },
  {
    slug: 'cuoco',
    name: 'Cuoco',
    description: 'Cuoco — Cuoco is a Rooster — Chef Rooster',
    subtitle: 'Introduction',
    italianMeaning: 'Cuoco is a Rooster — Chef Rooster',
    accentColor: '#d74a3e',
    accentHue: 10,
    category: 'person',
    traits: ['Friendly', 'Curious', 'Supportive', 'Playful'],
    portrait: '/characters/cuoco.png',
    showcase: '/characters/cuoco.png',
    voiceIntro: '/audio/cuoco-intro.mp3',
    videoSrc: '/videos/cuoco_idle.mp4',
    modes: {
      play: ['Story Time', 'Music & Rhythm', 'Geography', 'STEM Sparks'],
      learn: ['All Languages', 'Homework Helper', 'Coding'],
      support: ['Calm & Breathe', 'Milestones', 'Teaching Mode'],
    },
  },
  {
    slug: 'nonna',
    name: 'Nonna',
    description: 'Nonna — Nonna means Grandmother in Italian',
    subtitle: 'Introduction',
    italianMeaning: 'Nonna means Grandmother in Italian',
    accentColor: '#d7a36f',
    accentHue: 30,
    category: 'person',
    traits: ['Friendly', 'Curious', 'Supportive', 'Playful'],
    portrait: '/characters/nonna.png',
    showcase: '/characters/nonna.png',
    voiceIntro: '/audio/nonna-intro.mp3',
    videoSrc: '/videos/nonna_idle.mp4',
    modes: {
      play: ['Story Time', 'Music & Rhythm', 'Geography', 'STEM Sparks'],
      learn: ['All Languages', 'Homework Helper', 'Coding'],
      support: ['Calm & Breathe', 'Milestones', 'Teaching Mode'],
    },
  },
  {
    slug: 'cucita',
    name: 'Cucita',
    description: 'Cucita — Cucita means Sewn/Stitched in Italian',
    subtitle: 'Introduction',
    italianMeaning: 'Cucita means Sewn/Stitched in Italian',
    accentColor: '#d77f8a',
    accentHue: 350,
    category: 'object',
    traits: ['Friendly', 'Curious', 'Supportive', 'Playful'],
    portrait: '/characters/cucita.png',
    showcase: '/characters/cucita.png',
    voiceIntro: '/audio/cucita-intro.mp3',
    videoSrc: '/videos/cucita_idle.mp4',
    modes: {
      play: ['Story Time', 'Music & Rhythm', 'Geography', 'STEM Sparks'],
      learn: ['All Languages', 'Homework Helper', 'Coding'],
      support: ['Calm & Breathe', 'Milestones', 'Teaching Mode'],
    },
  },
  {
    slug: 'polpo',
    name: 'Polpo',
    description: 'Polpo — Polpo means Octopus in Italian',
    subtitle: 'Introduction',
    italianMeaning: 'Polpo means Octopus in Italian',
    accentColor: '#7a6fd7',
    accentHue: 250,
    category: 'animal',
    traits: ['Friendly', 'Curious', 'Supportive', 'Playful'],
    portrait: '/characters/polpo.png',
    showcase: '/characters/polpo.png',
    voiceIntro: '/audio/polpo-intro.mp3',
    videoSrc: '/videos/polpo_idle.mp4',
    modes: {
      play: ['Story Time', 'Music & Rhythm', 'Geography', 'STEM Sparks'],
      learn: ['All Languages', 'Homework Helper', 'Coding'],
      support: ['Calm & Breathe', 'Milestones', 'Teaching Mode'],
    },
  },
];

export function getCharacterBySlug(slug: string): Character | undefined {
  return characters.find((c) => c.slug === slug);
}